name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Automation Testing "]
    types:
      - completed

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check read env secrets
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Load secrets and save to app.env
        run: aws secretsmanager get-secret-value --secret-id amikompedia --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: beneboba/amikompedia:latest

  run-container:
    name: Run Docker image on self-hosted runner
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull beneboba/amikompedia:latest
        
      - name: Delete Old docker container
        run: sudo docker rm -f amikompedia-container || true
        
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name amikompedia-container beneboba/amikompediia
